{% set name = "xtensor" %}
{% set version = "0.10.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ../.

build:
  number: 0

requirements:
  build:
    - toolchain
    - cmake

test:
  commands:
    - test -d ${PREFIX}/include/xtensor  # [unix]
    - test -f ${PREFIX}/include/xtensor/xarray.hpp  # [unix]
    - test -f ${PREFIX}/share/cmake/xtensor/xtensorConfig.cmake  # [unix]
    - test -f ${PREFIX}/share/cmake/xtensor/xtensorConfigVersion.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\include\xtensor\xarray.hpp (exit 0) else (exit 1)  # [win]
    - if exist %PREFIX%\share\cmake\xtensorConfig.cmake (exit 0) else (exit 1)  # [win]
    - if exist %PREFIX%\share\cmake\xtensorConfigVersion.cmake (exit 0) else (exit 1)  # [win]

about:
  home: http://quantstack.net/xtensor
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'The C++ tensor algebra library'
  description: 'Multi dimensional arrays with broadcasting and lazy computing'
  doc_url: http://xtensor.readthedocs.io
  dev_url: https://github.com/QuantStack/xtensor

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
